#!/bin/sh
### BEGIN INIT INFO
# Provides:          mcp
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Armagetron Advanced daemon manager
# Description:       A complete multi-server management framework and web interface for Armagetron Advanced.
### END INIT INFO

case "$1" in
	start)
		echo -n "Starting MCP: "
		start-stop-daemon --start --quiet --exec /usr/bin/mcp --background --pidfile /var/run/mcp.pid --make-pidfile && echo "OK" || echo "Fail"
		;;
	stop)
		echo -n "Stopping MCP: "
		start-stop-daemon --stop --quiet --pidfile /var/run/mcp.pid && echo "OK" || echo "Fail"
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage:	$0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
