#!/usr/bin/env python3
import os
import sys

dir = sys.argv[1]
uid = int(sys.argv[2])
gid = int(sys.argv[3])
prog = sys.argv[4]
args = sys.argv[4:]

os.chroot(dir)
os.chdir('/')
os.setresgid(gid, gid, gid)
os.setresuid(uid, uid, uid)
os.execv(prog, args)
os.exit(1)
